version: "3.9"
services:
  web:
    image: fruocco/oai-embeddings
    ports:
      - "8082:80"
    env_file:
      - .env
    volumes:
      - '/root/docker/openai_embeddings_2/code/:/usr/local/src/myscripts'
    restart: always
    depends_on:
      api:
        condition: service_healthy
    command: sh -c "pip3 install -r requirements.txt && streamlit run OpenAI_Queries.py --server.port 80 --server.enableXsrfProtection false"
  api:
    image: redis/redis-stack-server:latest
    ports:
      - "6380:6379"
    env_file:
      - .env
    volumes:
      - /root/docker/openai_embeddings_data_2/:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s
  batch:
    image: fruocco/oai-batch:latest
    ports: 
      - "8083:80"
    env_file:
      - .env
    volumes:
      - '/root/docker/openai_embeddings_2/code/:/home/site/wwwroot'
    restart: always
    depends_on:
      api:
        condition: service_healthy
    command: sh -c "cd /home/site/wwwroot && pip3 install -r requirements.txt && /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost"
